#pragma once

#ifdef MOUSEKEY_ENABLE
  #define MOUSEKEY_DELAY 0
  #define MOUSEKEY_INTERVAL 16
  #define MOUSEKEY_MOVE_DELTA 5
  #define MOUSEKEY_MAX_SPEED 5
  #define MOUSEKEY_TIME_TO_MAX 64
  #define MOUSEKEY_WHEEL_DELAY 0
  #define MOUSEKEY_WHEEL_INTERVAL 100
  #define MOUSEKEY_WHEEL_MAX_SPEED 6
  #define MOUSEKEY_WHEEL_TIME_TO_MAX 255
#endif

#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD

#define TAPPING_TERM 175
#define ONESHOT_TAP_TOGGLE 5
#define ONESHOT_TIMEOUT 2085

// reduce filesize
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
